# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Create a new stage for the release image
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the built files and necessary package files
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package-lock.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Expose port (if necessary)
# EXPOSE 3000

# Define environment variables for the Google Cloud project and key file
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/key.json

# Define the entrypoint command
ENTRYPOINT ["node", "dist/index.js"]

# Default command arguments (these can be overridden at runtime)
CMD ["--project-id", "your-project-id", "--location", "us-central1"]